### ISSUE TITLE
Crie relacionamento entre model Cliente, Estado e Cidade

### ISSUE THREAD

**Issue by helioalb** [rubiabferreira/vittorana#2]
Muitos clientes pertencem a uma Cidade
Muitos clientes pertencem a um estado através de suas cidades [Associação through](http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association)

**Comment by rubiabferreira** [comment]
Vê se fiz certo? rsrs estou apanhando para commitar!

**Comment by helioalb** [comment]
Quase certo :smile: 
Cliente pertence a cidade (Cliente belongs_to :cidade) . Até aí certo.

Agora o lado da cidade: 
Pense em uma cidade como Londrina. E pense no cliente "Fulano". Londrina pertence a "Fulano"? Ou Londrina tem "Fulano"? E mais ainda. Londrina tem só "Fulano" ou tem além de "Fulano" mais muitos outros clientes?
Então ao invés de 

``` ruby
class Cidade < ActiveRecord::Base
  belongs_to :estado
  belongs_to :cliente , through :cidades
 end
```

o correto é:

``` ruby
class Cidade < ActiveRecord::Base
  belongs_to :estado
  has_many :clientes
end
```

A segunda parte agora.
Suponha que você queira saber quantos clientes existem no Paraná.
Para saber quantos clientes existem no Paraná você deveria pegar quantos clientes existem em cada cidade do Paraná e soma-los, certo?
O rails já resolve isso para você. Basta você declarar algo do tipo: Um **Estado** tem MUITOS **clientes** ATRAVÉS de suas **cidades**.
Então, ao invés disso:

``` ruby
class Estado < ActiveRecord::Base
   has_many :cidades
   belongs_to :cliente, through :cidades
end
```

tente isso:

``` ruby
class Estado < ActiveRecord::Base
   has_many :cidades
   has_many :clientes, through :cidades
end
```

Mais um detalhe. A população do banco ficou no arquivo _db/seed.rb_. Para carregar ele use `rake db:seed`. Procure deixar as migrations somente para a estrutura do banco.

**Comment by rubiabferreira** [comment]
Bom dia!

P**** Hélio, você é o cara. Realmente você vai ter paciência comigo? rsrsrs
Obrigada pela força. Ao final no meu projeto mando-te um presente.

Vou fazer isso e entendi agora claramente a relação "through"

Abraços!

Em 10 de abril de 2015 07:28, Helio Albano de Oliveira <
notifications@github.com> escreveu:
